export enum TripStatus {
  BOOKING = 'BOOKING',

  WAIT_FOR_DRIVER = 'WAIT_FOR_DRIVER',

  COMPLETED_BOOK = 'COMPLETED_BOOK',

  DRIVER_ARRIVED = 'DRIVER_ARRIVED',

  MOVING = 'MOVING',

  REVIEW = 'REVIEW',

  DONE = 'DONE',

  CANCELED = 'CANCELED',
}
